### ISSUE TITLE
Show contributed by on tips page

### ISSUE THREAD

**Issue by santoshyadavdev** [santoshyadavdev/GitHubTips#6]
ContributedBy is missing on the tips page, we need to display the same, we are already capturing the value

<img width="726" alt="image" src="https://user-images.githubusercontent.com/11923975/222197830-c118748c-9802-40a0-b66f-7152bd3d5e58.png">

**Comment by Yasir761** [comment]
I want to give it a try

**Comment by santoshyadavdev** [comment]
Go for it 😃
